### ISSUE TITLE
New version to support @hapi/good

### ISSUE THREAD

**Issue by PizzaBrandon** [nakardo/good-slack#24]
hapi is moving to using scoped packages (https://www.npmjs.com/package/@hapi/hapi) and upgrading breaks the peer dependency check.

I'm not sure if you can conditionally target two packages of different names, so this may require creating a new major version that tracks the @hapi packages in parallel.

**Comment by nakardo** [comment]
I think the `peerDependency` could be removed and just leave the compatibility note on the README as it is. It's also a good chance to update the other Hapi dependencies to scoped packages as you mentioned. Would you mind making the change?

**Comment by PizzaBrandon** [comment]
I'm already working on it. I hope to have it complete by my end of day.

**Comment by PizzaBrandon** [comment]
Does that PR look good to you?

**Comment by nakardo** [comment]
Sorry. I've been busy until now. I updated the PR with a few comments.

**Comment by PizzaBrandon** [comment]
PR updated
